Add back check for CONFIG_IPIPE_EXTENDED

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20777,6 +20777,11 @@ echo "${ECHO_T}Adeos newgen (I-pipe $v)" >&6
 echo "$as_me: error: Please activate the Adeos support in $XENO_LINUX_DIR and rebuild your kernel" >&2;}
    { (exit 1); exit 1; }; }
    fi
+   if test x${CONFIG_IPIPE_EXTENDED} = x; then
+      { { echo "$as_me:$LINENO: error: Please re-patch your kernel with the proper Adeos support (<= 1.0)" >&5
+echo "$as_me: error: Please re-patch your kernel with the proper Adeos support (<= 1.0)" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
 elif test -r $XENO_LINUX_SRCDIR/include/linux/adeos.h; then
    v=`grep '^#define.*ADEOS_ARCH_STRING.*"' $XENO_LINUX_SRCDIR/include/asm-$XENO_TARGET_ARCH/adeos.h|sed -e 's,.*"\(.*\)"$,\1,'`
    echo "$as_me:$LINENO: result: Adeos oldgen ($v)" >&5
