Bootstrap autoconf files

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21040,6 +21040,73 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+echo "$as_me:$LINENO: checking for pthread_spin_lock" >&5
+echo $ECHO_N "checking for pthread_spin_lock... $ECHO_C" >&6
+if test "${ac_cv_pthread_spin_lock+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  save_CFLAGS="$CFLAGS"
+ CFLAGS="-Wimplicit-function-declaration -Werror -D_GNU_SOURCE"
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pthread.h>
+int
+main ()
+{
+pthread_spinlock_t lock; pthread_spin_init(&lock, 0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_pthread_spin_lock=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_pthread_spin_lock=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ if test $ac_cv_pthread_spin_lock = yes ; then
+     echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PTHREAD_SPIN_LOCK 1
+_ACEOF
+
+ else
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+ fi
+ CFLAGS="$save_CFLAGS"
+fi
+
+
 echo "$as_me:$LINENO: checking for specific GCC switches" >&5
 echo $ECHO_N "checking for specific GCC switches... $ECHO_C" >&6
 if test "${ac_cv_gcc_wnoalias+set}" = set; then
