Introduce *USER_LDFLAGS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP target target_cpu target_vendor target_os CC CFLAGS CPPFLAGS CC_FOR_BUILD ac_ct_CC_FOR_BUILD CPP CPPFLAGS CPP_FOR_BUILD BUILD_EXEEXT BUILD_OBJEXT CFLAGS_FOR_BUILD CPPFLAGS_FOR_BUILD CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT XENO_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_XENO_UVM_TRUE CONFIG_XENO_UVM_FALSE CONFIG_XENO_DOC_DOX_TRUE CONFIG_XENO_DOC_DOX_FALSE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE XENO_TARGET_ARCH XENO_BUILD_STRING XENO_HOST_STRING XENO_USER_CFLAGS XENO_USER_APP_CFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP target target_cpu target_vendor target_os CC CFLAGS CPPFLAGS CC_FOR_BUILD ac_ct_CC_FOR_BUILD CPP CPPFLAGS CPP_FOR_BUILD BUILD_EXEEXT BUILD_OBJEXT CFLAGS_FOR_BUILD CPPFLAGS_FOR_BUILD CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT XENO_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT DBX_DOC_ROOT DBX_DOC_TRUE DBX_DOC_FALSE DBX_GEN_DOC_ROOT DBX_LINT DBX_XSLTPROC DBX_FOP DBX_MAYBE_NONET DBX_ROOT DBX_XSL_ROOT DBX_ABS_SRCDIR_TRUE DBX_ABS_SRCDIR_FALSE CONFIG_XENO_UVM_TRUE CONFIG_XENO_UVM_FALSE CONFIG_XENO_DOC_DOX_TRUE CONFIG_XENO_DOC_DOX_FALSE DOXYGEN_SHOW_INCLUDE_FILES LATEX_BATCHMODE LATEX_MODE XENO_TARGET_ARCH XENO_BUILD_STRING XENO_HOST_STRING XENO_USER_CFLAGS XENO_USER_LDFLAGS XENO_USER_APP_CFLAGS XENO_USER_APP_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20522,8 +20522,8 @@ case "$host" in
  bfin-*|bfinnommu-*|blackfin-*)
 	XENO_TARGET_ARCH=bfinnommu
 	if test x$enable_shared = xyes; then
-	   { { echo "$as_me:$LINENO: error: Shared libraries unsupported -- use --disable-shared" >&5
-echo "$as_me: error: Shared libraries unsupported -- use --disable-shared" >&2;}
+	   { { echo "$as_me:$LINENO: error: Shared libraries unsupported -- reconfigure passing --disable-shared" >&5
+echo "$as_me: error: Shared libraries unsupported -- reconfigure passing --disable-shared" >&2;}
    { (exit 1); exit 1; }; }
 	fi
         ;;
@@ -21374,6 +21374,7 @@ echo "$as_me:$LINENO: result: done" >&5
 echo "${ECHO_T}done" >&6
 
 XENO_USER_CFLAGS="-D_GNU_SOURCE -D_REENTRANT -D__XENO__"
+XENO_USER_LDFLAGS=
 
 case $XENO_TARGET_ARCH in
  i386)
@@ -21387,6 +21388,9 @@ case $XENO_TARGET_ARCH in
         ;;
  bfinnommu)
 	XENO_USER_CFLAGS="$XENO_USER_CFLAGS -Wall -pipe"
+	# uClinux wants flat format executables; assume that our
+	# source format is ELF.
+	XENO_USER_LDFLAGS="-Wl,-elf2flt"
         ;;
 esac
 
@@ -21398,6 +21402,9 @@ fi
 
 XENO_USER_APP_CFLAGS=$XENO_USER_CFLAGS
 XENO_USER_CFLAGS="$XENO_USER_CFLAGS -D__IN_XENO__ -Wstrict-prototypes"
+XENO_USER_APP_LDFLAGS=$XENO_USER_LDFLAGS
+
+
 
 
 
@@ -22288,7 +22295,9 @@ s,@XENO_TARGET_ARCH@,$XENO_TARGET_ARCH,;t t
 s,@XENO_BUILD_STRING@,$XENO_BUILD_STRING,;t t
 s,@XENO_HOST_STRING@,$XENO_HOST_STRING,;t t
 s,@XENO_USER_CFLAGS@,$XENO_USER_CFLAGS,;t t
+s,@XENO_USER_LDFLAGS@,$XENO_USER_LDFLAGS,;t t
 s,@XENO_USER_APP_CFLAGS@,$XENO_USER_APP_CFLAGS,;t t
+s,@XENO_USER_APP_LDFLAGS@,$XENO_USER_APP_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
