bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1562,8 +1562,8 @@ Optional Features:
   --enable-x86-tsc        Enable x86 TSC for timings
   --enable-arm-mach       Select for which machine we are compiling. Valid
                           machines are at91rm9200, at91sam926x, generic, imx,
-                          imx21, integrator, ixp4xx, pxa, pxa3xx, s3c2410,
-                          sa1100.
+                          imx21, integrator, ixp4xx, mx2, mx3, pxa, pxa3xx,
+                          s3c2410, sa1100.
   --enable-arm-arch=<version>
                           Select ARM architecture version, if the machine
                           selected with --enable-arm-mach supports several
@@ -1620,6 +1620,8 @@ Optional Packages:
   --with-dbx-xsl-root     specify the Docbook XML XSL stylesheet root. Default
                           is to use well-known locations (or network if
                           --enable-dbx-network was passed)
+  --without-__thread      do not use TLS features (allows for dlopen'ing
+                          Xenomai libs)
 
 Some influential environment variables:
   CC          C compiler command
@@ -5722,7 +5724,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5725 "configure"' > conftest.$ac_ext
+  echo '#line 5727 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8549,11 +8551,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8554: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8556: \$? = $ac_status" >&5
+   echo "$as_me:8558: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8839,11 +8841,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8842: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8844: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8846: \$? = $ac_status" >&5
+   echo "$as_me:8848: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8943,11 +8945,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8946: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8948: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8950: \$? = $ac_status" >&5
+   echo "$as_me:8952: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11320,7 +11322,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11323 "configure"
+#line 11325 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11420,7 +11422,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11423 "configure"
+#line 11425 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13821,11 +13823,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13824: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13826: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13828: \$? = $ac_status" >&5
+   echo "$as_me:13830: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13925,11 +13927,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13928: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13930: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13932: \$? = $ac_status" >&5
+   echo "$as_me:13934: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15523,11 +15525,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15526: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15528: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15530: \$? = $ac_status" >&5
+   echo "$as_me:15532: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15627,11 +15629,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15630: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15634: \$? = $ac_status" >&5
+   echo "$as_me:15636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17847,11 +17849,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17850: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17852: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17854: \$? = $ac_status" >&5
+   echo "$as_me:17856: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18137,11 +18139,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18142: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18144: \$? = $ac_status" >&5
+   echo "$as_me:18146: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18241,11 +18243,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18244: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18246: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18248: \$? = $ac_status" >&5
+   echo "$as_me:18250: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21257,27 +21259,27 @@ fi
 { echo "$as_me:$LINENO: checking for target architecture" >&5
 echo $ECHO_N "checking for target architecture... $ECHO_C" >&6; }
 
-CONFIG_XENO_FASTSEM=
+CONFIG_XENO_FASTSYNCH=
 case "$host" in
  i*86*-*)
 	XENO_TARGET_ARCH=x86
         XENO_LINUX_ARCH=i386
 	XENO_LINUX_INSTALL_TARGET=install
-	CONFIG_XENO_FASTSEM=y
+	CONFIG_XENO_FASTSYNCH=y
         ;;
  powerpc-*|ppc-*)
 	XENO_TARGET_ARCH=powerpc
         XENO_LINUX_ARCH=ppc
 	XENO_LINUX_INSTALL_TARGET=install_image
 	XENO_LINUX_IMAGE=arch/ppc/boot/images/zImage.elf
-	CONFIG_XENO_FASTSEM=y
+	CONFIG_XENO_FASTSYNCH=y
         ;;
  powerpc64-*|ppc64-*)
 	XENO_TARGET_ARCH=powerpc
         XENO_LINUX_ARCH=ppc64
 	XENO_LINUX_INSTALL_TARGET=install_image
 	XENO_LINUX_IMAGE=arch/ppc64/boot/images/zImage
-	CONFIG_XENO_FASTSEM=y
+	CONFIG_XENO_FASTSYNCH=y
         ;;
  ia64-*)
 	XENO_TARGET_ARCH=ia64
@@ -21294,14 +21296,14 @@ case "$host" in
  	XENO_LINUX_ARCH=arm
 	XENO_LINUX_INSTALL_TARGET=install_image
 	XENO_LINUX_IMAGE=arch/arm/boot/zImage
-	# We set CONFIG_XENO_FASTSEM later, when we know what architecture we
+	# We set CONFIG_XENO_FASTSYNCH later, when we know what architecture we
 	# are running
 	;;
  x86_64-*|amd64-*)
 	XENO_TARGET_ARCH=x86
         XENO_LINUX_ARCH=x86_64
 	XENO_LINUX_INSTALL_TARGET=install
-	CONFIG_XENO_FASTSEM=y
+	CONFIG_XENO_FASTSYNCH=y
         ;;
  *) echo ""
    echo "*******************************************"
@@ -21402,10 +21404,10 @@ echo $ECHO_N "checking for ARM machine... $ECHO_C" >&6; }
 if test "${enable_arm_mach+set}" = set; then
   enableval=$enable_arm_mach; case "$enableval" in
 	at91rm9200)   	arch=4
-	        	tsc_type=__XN_TSC_TYPE_FREERUNNING;;
+	        	tsc_type=__XN_TSC_TYPE_FREERUNNING_FAST_WRAP;;
 
 	at91sam926x)   	arch=5
-	        	tsc_type=__XN_TSC_TYPE_FREERUNNING;;
+	        	tsc_type=__XN_TSC_TYPE_FREERUNNING_FAST_WRAP;;
 
 	generic)	arch=4
 			CONFIG_XENO_ARM_SA1100=y
@@ -21420,7 +21422,16 @@ if test "${enable_arm_mach+set}" = set; then
 	integrator) 	arch=choose
 			unset tsc_type;;
 
-	ixp4xx|pxa) 	arch=5
+	ixp4xx)		arch=5
+	      		tsc_type=__XN_TSC_TYPE_FREERUNNING;;
+
+	mx2)		arch=5
+			tsc_type=__XN_TSC_TYPE_FREERUNNING;;
+
+	mx3)		arch=6
+			tsc_type=__XN_TSC_TYPE_FREERUNNING;;
+
+	pxa) 		arch=5
 	      		tsc_type=__XN_TSC_TYPE_FREERUNNING;;
 
 	pxa3xx)	        arch=xscale3
@@ -21522,7 +21533,7 @@ fi
 echo "${ECHO_T}${CONFIG_XENO_ARM_EABI:-no}" >&6; }
 
   if test $CONFIG_XENO_ARM_ARCH -ge 6 || test x$CONFIG_SMP != xy; then
-	CONFIG_XENO_FASTSEM=y
+	CONFIG_XENO_FASTSYNCH=y
   fi
 fi
 
@@ -21970,8 +21981,8 @@ fi
 
 
 
-# Extract the first word of "fop.sh", so it can be a program name with args.
-set dummy fop.sh; ac_word=$2
+# Extract the first word of "fop", so it can be a program name with args.
+set dummy fop; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_prog_DBX_FOP+set}" = set; then
@@ -21987,7 +21998,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_DBX_FOP="fop.sh"
+    ac_cv_prog_DBX_FOP="fop"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -22008,8 +22019,8 @@ fi
 
 
 if test x"$DBX_FOP" = x -a -n "$DBX_DOC"; then
-   { { echo "$as_me:$LINENO: error: fop.sh was not found. Check your PATH variable and try again." >&5
-echo "$as_me: error: fop.sh was not found. Check your PATH variable and try again." >&2;}
+   { { echo "$as_me:$LINENO: error: fop was not found. Check your PATH variable and try again." >&5
+echo "$as_me: error: fop was not found. Check your PATH variable and try again." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -22328,9 +22339,9 @@ cat >>confdefs.h <<\_ACEOF
 #define CONFIG_SMP 1
 _ACEOF
 
-test x$CONFIG_XENO_FASTSEM = xy &&
+test x$CONFIG_XENO_FASTSYNCH = xy &&
 cat >>confdefs.h <<\_ACEOF
-#define CONFIG_XENO_FASTSEM 1
+#define CONFIG_XENO_FASTSYNCH 1
 _ACEOF
 
 test x$CONFIG_X86_TSC = xy &&
@@ -22830,6 +22841,47 @@ fi
 done
 
 LIBS="$save_LIBS"
+
+
+# Check whether --with-__thread was given.
+if test "${with___thread+set}" = set; then
+  withval=$with___thread; use__thread=$withval
+else
+  use__thread=yes
+fi
+
+
+if test "x$use__thread" != xno; then
+	{ echo "$as_me:$LINENO: checking for __thread" >&5
+echo $ECHO_N "checking for __thread... $ECHO_C" >&6; }
+if test "${libc_cv_gcc___thread+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat > conftest.c <<\EOF
+__thread int a __attribute__ ((tls_model ("initial-exec"))) = 42;
+EOF
+	if { ac_try='${CC-cc} $CFLAGS $CPPFLAGS -c -Werror conftest.c >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+		libc_cv_gcc___thread=yes
+	else
+		libc_cv_gcc___thread=no
+	fi
+	rm -f conftest*
+fi
+{ echo "$as_me:$LINENO: result: $libc_cv_gcc___thread" >&5
+echo "${ECHO_T}$libc_cv_gcc___thread" >&6; }
+	if test "$libc_cv_gcc___thread" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE___THREAD 1
+_ACEOF
+
+	fi
+fi
 
 
 
