Fix issues w/ gcc 4.x

diff --git a/sim/configure b/sim/configure
--- a/sim/configure
+++ b/sim/configure
@@ -19805,6 +19805,66 @@ if test $ac_cv_using_gcc_for_mvm_cxx = yes; then
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 save_CXXFLAGS="$CXXFLAGS"
+
+echo "$as_me:$LINENO: checking if C++ compiler supports -fwritable-strings -fdollars-in-identifiers" >&5
+echo $ECHO_N "checking if C++ compiler supports -fwritable-strings -fdollars-in-identifiers... $ECHO_C" >&6
+CXXFLAGS="-fwritable-strings -fdollars-in-identifiers -Werror"
+if test "${ac_cv_cxx_mvm_wsdollars+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+int i = 0; return i;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_mvm_wsdollars="-fwritable-strings -fdollars-in-identifiers"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_mvm_wsdollars=""
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+if test -z "$ac_cv_cxx_mvm_wsdollars"; then
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+else
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
 echo "$as_me:$LINENO: checking if C++ compiler supports -fno-exceptions" >&5
 echo $ECHO_N "checking if C++ compiler supports -fno-exceptions... $ECHO_C" >&6
 CXXFLAGS="-fno-exceptions -Werror"
@@ -19923,7 +19983,7 @@ else
 echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 fi
-MVM_CXXFLAGS="-fwritable-strings -fdollars-in-identifiers $ac_cv_cxx_mvm_noex $ac_cv_cxx_mvm_nonnull"
+MVM_CXXFLAGS="$ac_cv_cxx_mvm_wsdollars $ac_cv_cxx_mvm_noex $ac_cv_cxx_mvm_nonnull"
 CXXFLAGS="$save_CXXFLAGS"
 else
 echo "$as_me:$LINENO: result: no" >&5
