lib/cobalt: allow for overriding Cobalt service implementation
We provide a mean for overriding Cobalt wrapper routines with
user-provided routines.

Each "foo" Cobalt routine shadowing a POSIX service may then appear
as:

__real_foo() => Original POSIX implementation.
__cobalt_foo() => Cobalt implementation.
__wrap_foo() => Weak alias to __cobalt_foo(). May be overriden
by some extension library.

Extension libraries overriding some of the shadowed POSIX routines
shall provide:

* Their own implementation of the POSIX service as __wrap_foo()
* An entry for the "foo" symbol in some override definition file, to
be installed in $(prefix)/lib, and named after the interface. This
file must have the same format than lib/cobalt/cobalt.wrappers.

E.g. a new interface "foo" overriding POSIX symbols should install a
file named $(prefix)/lib/foo.wrappers. This file will be picked
automatically by the xeno-config script when built for the Cobalt
core.

The Cobalt implementation of any overriden "foo" routine is still
callable as __COBALT(foo(args...)). Any call reference to foo() will
branch to the user-defined implementation overriding Cobalt's.

e.g. Library "foo" wants to provide its own implementation of service
sched_yield().

lib/foo
	/foo.wrappers
		...
		--wrap sched_yield
		...

	/pthread.c
		int __wrap_sched_yield(void)
		{
			/* Eventually branch to Cobalt's version. */
			return __COBALT(sched_yield());
		}

A Makefile rule should install lib/foo/foo.wrappers into $(prefix)/lib.

$ cd buildir
$ .../xenomai/configure --with-cobalt-override=.../lib/overlib/overlib.wrappers

NOTE: for pratical reasons, xeno-config and wrap-link.sh scripts
expect all POSIX wrapper files to match the "*.wrappers" glob pattern.

diff --git a/scripts/xeno-config-cobalt.in b/scripts/xeno-config-cobalt.in
--- a/scripts/xeno-config-cobalt.in
+++ b/scripts/xeno-config-cobalt.in
@@ -14,29 +14,28 @@ XENO_PREFIX="${staging}${prefix}"
 XENO_CC="@CC@"
 XENO_TARGET_ARCH="@XENO_TARGET_ARCH@"
 XENO_BASE_CFLAGS="-I${staging}${includedir} @XENO_USER_APP_CFLAGS@ -D__COBALT__"
-XENO_BASE_LDFLAGS="-L${staging}${libdir} -lpthread -lrt @XENO_USER_APP_LDFLAGS@"
 XENO_POSIX_LDFLAGS="-L${staging}${libdir} -lcobalt -lpthread -lrt @XENO_USER_APP_LDFLAGS@"
-XENO_POSIX_WRAPPERS="${staging}${libdir}/posix.wrappers"
-XENO_POSIX_FAST_WRAPPING="@LD_FILE_OPTION@"
 XENO_LIBRARY_DIR="${staging}${libdir}"
 XENO_INCLUDE_DIR="${staging}${includedir}"
+LD_FILE_OPTION="@LD_FILE_OPTION@"
 
 unset prefix exec_prefix libdir datadir datarootdir pkgdatadir includedir skin_list
 
-posix_ldflags ()
+dump_wrappers()
 {
-    if test \! -r $XENO_POSIX_WRAPPERS; then
-	echo "POSIX support is not available" >&2
-	exit 1
-    fi
-    if test "$XENO_POSIX_FAST_WRAPPING" = "yes"; then
-	echo -n "-Wl,@$XENO_POSIX_WRAPPERS $XENO_POSIX_LDFLAGS"
-    else
-	wrappers=`while read wrap_option symbol; do \
-		      echo -n "-Wl,$wrap_option,$symbol " ; \
-		  done < $XENO_POSIX_WRAPPERS`
-	echo -n "$wrappers $XENO_POSIX_LDFLAGS"
-    fi
+   file=$1
+   if test \! -r ${XENO_LIBRARY_DIR}/$file; then
+      echo "Xenomai: POSIX wrappers cannot be read from ${XENO_LIBRARY_DIR}/${file}" >&2
+      exit 1
+   fi
+   if test "$LD_FILE_OPTION" = "yes"; then
+      echo -n "-Wl,@${XENO_LIBRARY_DIR}/${file}"
+   else
+      wrappers=`while read wrap_option symbol; do	\
+	      echo -n "-Wl,$wrap_option,$symbol " ; \
+      done < ${XENO_LIBRARY_DIR}/${file}`
+      echo -n "$wrappers"
+   fi
 }
 
 usage ()
@@ -128,7 +127,6 @@ while test $# -gt 0; do
 	    done
 	    echo $cflags
 	    ;;
-
 	--ldflags)
 	    if test -z "$skin_list"; then
 		echo "no skin specified, missing --skin before --ldflags" 1>&2
@@ -142,8 +140,10 @@ while test $# -gt 0; do
 			;;
 		    vxworks|psos|alchemy)
 			copperplate=-lcopperplate
-			echo "-l$skin $ldflags"
-			echo
+			ldflags="$ldflags -l$skin"
+			if [ -r ${XENO_LIBRARY_DIR}/${skin}.wrappers ]; then
+			    ldflags=" `dump_wrappers ${skin}.wrappers` $ldflags"
+			fi
 			;;
 		    *)
 			echo "unknown skin: $skin" 1>&2
@@ -151,8 +151,8 @@ while test $# -gt 0; do
 			;;
 		esac
 	    done
-	    echo "$ldflags $copperplate"
-	    posix_ldflags; echo
+	    dump_wrappers cobalt.wrappers
+	    echo "$ldflags $copperplate $XENO_POSIX_LDFLAGS"
 	    ;;
 	--core)
 	    echo cobalt
