Improve busybox support and fix various glitches
git-svn-id: svn+ssh://svn.gna.org/svn/xenomai/trunk@1259 c6d672ea-8702-0410-b560-f74c916a59fe

diff --git a/scripts/xeno-test.in b/scripts/xeno-test.in
--- a/scripts/xeno-test.in
+++ b/scripts/xeno-test.in
@@ -1,5 +1,7 @@
-#!/bin/bash
-
+#! /bin/sh
+# Adapted to be run also under the BusyBox. If you want to test it under the BusyBox use
+# busybox sh xeno-test 
+# A BusyBox >= 1.1.3 with a make defconfig should provide all needed applets.
 myusage() {
     cat >&1 <<EOF
 xeno-test [options]
@@ -37,10 +39,51 @@ EOF
     exit 1
 }
 
+echo "xeno-test: started $*"
 #set -e	# ctrl-C's should end everything, not just subshells. 
 	# commenting it out may help to debug stuff.
 
 set -o notify	# see dd's finish immediately.(or not!)
+
+withBusybox=0
+if sh --help 2>&1| grep -q BusyBox; then
+    withBusybox=1;
+# else running a real /bin/sh (bash) shell
+fi
+echo withBusybox is $withBusybox
+pidFile=/var/lock/`basename $0.$$`.pids
+
+checkUtilities() {
+  # Check for needed helper utilities
+  local neededApplets="awk basename cut date dd dirname egrep grep getopt
+		       head kill md5sum mount sleep test top uname zcat"
+  local foundAll=1
+  for  _j in $neededApplets
+  do
+    if test -z "`which $_j`"; then
+      echo "Please build busybox with support for applet $_j"
+      foundAll=0
+    fi
+  done
+  if test $foundAll -eq 0 ; then exit 3 ; fi
+}
+
+checkHelpers() {
+  local foundAll=1
+  if test -z "`which script`" -a -n "$logging"; then
+      echo "You will not be able to log (-L option) as script is missing"
+      foundAll=0
+  fi
+  if test -z "`which mail`" -a "$sendit" = 'm' ; then
+      echo "You will not be able send mail (-m/-M options) as mail is missing"
+      foundAll=0
+  fi
+  if test -z "`which curl`" -a "$sendit" = 'm' ; then
+      echo "You will not be able to upload (-U option) as curl is missing"
+      foundAll=0
+  fi
+  if test $foundAll -eq 0 ; then exit 3 ; fi
+}
 
 loudly() {
     [ "$1" = "" ] && return
@@ -53,31 +96,46 @@ loudly() {
 
 # defaults for cpu workload 
 device=/dev/zero	
-typeset -a dd_jobs
-dd_jobs=()
+dd_jobs=
 
 # used in generate-loads
-mkload() { exec dd if=$device of=/dev/null $* ; }
+mkload() { dd if=$device of=/dev/null $* & }
 
 generate_loads() {
-    local jobsct=$1; shift;
+    local jobsct=$1;
+    # if test -z "$1"; then echo Skipping generate_loads; return; fi
+    shift 1
+    if test 0 -eq $withBusybox ; then
+	reaper() { echo something died a $! or $* ; sleep 1;  }
+	trap reaper CHLD
+	trap cleanup_load EXIT	# under all exit conditions
+    fi
+    while test $jobsct -ge 1; do 
+        jobsct=$((jobsct-1)); 
+        mkload
+        dd_jobs="$dd_jobs $!" ;
+    done
 
-    reaper() { echo something died $*; }
-    trap reaper CHLD
-    trap cleanup_load EXIT	# under all exit conditions
-    
-    for (( ; $jobsct ; jobsct-- )) ; do
-	mkload &
-	dd_jobs[${#dd_jobs[*]}]=$!
-    done;
-
-    echo dd workload started, pids ${dd_jobs[*]}
+    echo dd workload started, pids $dd_jobs stored in $pidFile
+    echo  $dd_jobs > $pidFile
 }
 
 cleanup_load() {
     # kill the workload
-    echo killing workload pids ${dd_jobs[*]}
-    kill ${dd_jobs[*]};
+    if test -z "$dd_jobs" -a -r $pidFile; then
+      dd_jobs=`cat $pidFile`
+      rm -f $pidFile
+    fi
+
+    if test -z "$dd_jobs" ; then
+        echo "cleanup_load: no dd_jobs found"
+    else
+	for _j in $dd_jobs
+	do
+	  ps | grep $_j
+	  kill $_j
+	done
+    fi
     unset dd_jobs;
 }
 
@@ -85,21 +143,20 @@ whatconf="XENO|IPIPE|PREEMPT|CONFIG_ACPI|CONFIG_PM|CPU_FREQ|CONFIG_DEBUG_SPINLOC
 
 
 boxinfo() { # static info, show once
-
-    loudly ./xeno-config --verbose
-    loudly ./xeno-info
+    loudly `dirname $0`/xeno-config --verbose
+    loudly `dirname $0`/xeno-info
 
     loudly cat /proc/cpuinfo	# bogomips changes under CPU_FREQ
-    loudly cksum /proc/cpuinfo	'# cpuinfo fingerprint'
+    loudly md5sum /proc/cpuinfo	'# cpuinfo fingerprint'
 
     # how much of the config do we want ?
-    local cmd="zgrep -E '$whatconf'"
-    [ "$verbose" = 1 ] && cmd=cat
-
-    if [ -f /proc/config.gz ]; then	# get the config
-	loudly $cmd /proc/config.gz
-    elif [ -f /lib/modules/`uname -r`/build/.config ]; then
-	loudly $cmd /lib/modules/`uname -r`/build/.config
+    local filter=" grep -E '$whatconf'"
+    [ "$verbose" = 1 ] && filter=
+    if test -f /proc/config.gz; then # get the config
+         loudly zcat /proc/config.gz | $filter
+    elif test -f /lib/modules/`uname -r`/build/.config
+    then
+	loudly cat /lib/modules/`uname -r`/build/.config | $filter
     fi
 
     [ -d /proc/adeos ] && for f in /proc/adeos/*; do loudly cat $f; done
@@ -107,7 +164,6 @@ boxinfo() { # static info, show once
 }
 
 boxstatus() {     # get dynamic status
-
     loudly cat /proc/interrupts
     loudly cat /proc/loadavg
     loudly cat /proc/meminfo
@@ -117,7 +173,11 @@ boxstatus() {     # get dynamic status
 	for f in /proc/xenomai/*/*; do [ -f $f ] && loudly cat $f; done
     fi
     [ -n "$prepost" ] && loudly $prepost
-    loudly top -bn1c | head -n $(( 12 + $workload ))
+    if test 0 -eq $withBusybox ; then
+	loudly top -bn1c | head -n $(( 12 + $workload ))
+    else
+	loudly top | head -n $(( 12 + $workload ))
+    fi
 }
 
 
@@ -129,24 +189,33 @@ run_w_load() {
     loudly generate_loads $workload
     boxstatus
     (
-	cd ../testsuite/latency
+        cd `dirname $0`/../testsuite/latency
 	loudly ./run --  $opts -t0
 	loudly ./run --  $opts -t1
 	loudly ./run --  $opts -t2
     )
-    (	cd ../testsuite/switch 
+    (	cd `dirname $0`/../testsuite/switch
 	loudly ./run --  '# switch'
     )
-    (	cd ../testsuite/cyclic
+    (	cd `dirname $0`/../testsuite/cyclic
 	loudly ./run -- -p 10 -n -l 1000 '# cyclictest'
     )
-
     boxstatus
+    cleanup_load
 }
-
 
 #####################
 # MAIN
+checkUtilities
+
+if [ -f /proc/config.gz ] ; then
+
+    # check/warn on problem configs
+    eval `zcat /proc/config.gz | grep CONFIG_CPU_FREQ` ;
+    if [ ! -z "$CONFIG_CPU_FREQ" ] ; then
+	echo "warning: CONFIG_CPU_FREQ=$CONFIG_CPU_FREQ may be problematic"
+    fi
+fi
 
 workload=1	# default = 1 job
 
@@ -155,7 +224,7 @@ pass=		# pass thru to latency
 loadpass=	# pass thru to subshell, not to actual tests
 
 logging=	# no logging by default
-logfile=	# defaults to test-`uname -r`-<datestampe>
+logfile=test-`uname -r` # defaults to test-`uname -r`-<datestampe>
 logprefix=/tmp/	# someplace usually there
 prepost=	# command to run pre, and post test (ex ntpq -p)
 
@@ -168,18 +237,20 @@ dateargs='+%y%m%d.%H%M%S'
 
 sendit() {
     local file=$1
-    
-    if [ "$sendit" == 'm' ]; then
+    if test "$sendit" = 'm' ; then
 	echo "mailing $file to $email"
-	if [ "$file" != '' ]; then
+	if test -n "$file" ; then
 	    mail -s 'xeno-test results' $email -- -F $sentby < $file
 	else
 	    cat - | mail -s 'xeno-test results' $email -- -F $sentby
 	fi
-    elif [ "$sendit" == 'u' ]; then
+    elif test "$sendit" = 'u' ; then
+	echo "uploading $file to $url"
 	which curl && curl -T $file $url
 	# -x $proxy >/tmp/.submit_result
 	# which wget && curl -T $file $url \
+    else
+	echo "sendit unsupported option '$sendit'"
     fi
 }
 
@@ -199,7 +270,7 @@ handle_options() {	# called for XENOTEST_OPTS, ARGV
 	    if !(mount | grep -q ^$device) ; then
 		echo d option must be a block device, ie one of:
 		mount | cut -d\  -f1 | egrep -ve 'sysfs|proc|depts'
-		exit;
+		exit 1;
 	    fi
 	    loadpass="$loadpass -d $device"
 	    ;;
@@ -238,34 +309,46 @@ handle_options() {	# called for XENOTEST_OPTS, ARGV
 }
 
 # process options from envar, then from cmd-line
-while getopts 'd:shqT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO $XENOTEST_OPTS ; do
+while getopts 'd:shqvT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO $XENOTEST_OPTS ; do
     handle_options;
 done
-while getopts 'd:shqT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO ; do
+while getopts 'd:shqvT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO ; do
     handle_options;
 done
+
+checkHelpers
 
 # all args have been handled, and split into 2 passthrus
 shift $(($OPTIND - 1));
 
+if test -f pidFile && ! test -w $pidFile ; then
+  echo  "pidfile $pidFile not writable "; 
+  exit 4
+fi
 
-if [ "$logging" != "" ]; then
+echo "xeno-test: running tests"
+
+wfile=$logprefix$logfile-`date $dateargs`
+if test "$logging" != "" ; then
     # restart inside a script invocation, passing appropriate args
-    wfile=$logprefix$logfile-`date $dateargs`
-    script -c "./xeno-test $loadpass $pass $*" $wfile && sendit $wfile
+    script -c "`dirname $0`/xeno-test $loadpass $pass $*" $wfile
+    res="$?"
+    if test "$res" == "0" ; then
+	sendit $wfile
+    fi
 else
-    if [ "$altwork" != "" ]; then
+    if test "$altwork" != "" ; then
 	mkload() { exec $altwork; }
     fi
-    echo starting $0 $pass $loadpass $*
-    if [ "$sendit" != '' ]; then
-	run_w_load $pass $* 2>&1 | sendit
-    else
-	run_w_load $pass $*
+    run_w_load $pass $* 2>&1 | tee $wfile
+    res="$?"
+    if test "$sendit" != '' && test $res -eq 0  ; then
+       sendit $wfile
     fi
 fi
 
-exit;
+echo "xeno-test: finished"
+exit 0
 
 
 #################################################
@@ -297,15 +380,20 @@ separate window, or when it finishes.  Forex, 'dd if=/dev/hda ...'
 will eventually finish, and should be restarted to keep the load up.
 Figure out why killall didnt work properly.
 
-2. Much more testing.  Heres a weak start..
+2. Much more testing.  Heres a weak start. You migth be better off
+using and improving test/test-xeno-test.rb.
 
 #!/bin/bash
 PATH=.:$PATH
 xeno-test -L
 xeno-test -N foo -T 18 -l 6 -s
 xeno-test -L -N foo1-
+xeno-test -m
+xeno-test -T 1 -M $USER@localhost
 xeno-test -N foo0 -w0 -l 5 -T 30 -h
 xeno-test -L -N foo4- -w4
 xeno-test -L -N foo4W- -w4 -W 'dd if=/dev/hda1 of=/dev/null'
 
-3.
+3. Repeat the same tests under the BusyBox.
+
+4. Check for border cases like missing awk, curl, mail, script, /proc/config.gz
