Release v2.2
git-svn-id: svn+ssh://svn.gna.org/svn/xenomai/tags/v2.2.0@1341 c6d672ea-8702-0410-b560-f74c916a59fe

diff --git a/scripts/xeno-test.in b/scripts/xeno-test.in
--- a/scripts/xeno-test.in
+++ b/scripts/xeno-test.in
@@ -1,9 +1,11 @@
-#!/bin/bash
-
+#! /bin/sh
+# Adapted to be run also under the BusyBox. If you want to test it under the BusyBox use
+# busybox sh xeno-test 
+# A BusyBox >= 1.1.3 with a make defconfig should provide all needed applets.
 myusage() {
     cat >&1 <<EOF
 xeno-test [options]
-  runs latency and klatency tests
+  runs latency test in all 3 test-modes
   -w <number>	spawn N workloads (dd if=/dev/zero of=/dev/null) default=1
   -d <device>	used as alternate src in workload (dd if=$device ..)
 		The device must be mounted, and (unfortunately) cannot
@@ -12,183 +14,342 @@ xeno-test [options]
   -W <script>   script is an alternate workload.  If you need to pass args
 		to your program, use quotes.  The program must clean
 		up its children when it gets a SIGTERM
-  -p <cmd>	cmd is run before, between and after latency, klatency tests
+  -P <cmd>	cmd is run before and after rt-tests
 		(forex: 'ntpdate -b <host>' or 'ntpq -p')
-  -L	     	writes to logfile (default "test-`uname -r`") (via script)
-  -N <name>	same as -L, but prepend "$name-" (without -L, logname="$name-")
-		prepending allows you to give a full path.
+  -L	     	writes logs to /tmp/test-`uname -r`-<timestamp>
+  -N <name>	like -L, but writes to name-<timestamp> (in PWD)
+		name can be full or relative pathname
+  -v		verbose
+  -M <email>	sends output to given addr
+  -m		sends output to xenomai-data@gna.org
+  -U <url>	uploads output to given URL
+  -D <datefmt>	alternate options to date, for timestamp (dflt: 
 
-  # following options are passed thru to latency, klatency
+  # following options are passed thru to latency
   -s	print statistics of sampled data (default on)
-  -h	print histogram of sampled data (default on)
+  -h	print histogram of sampled data (default on, implies -s)
   -q	quiet, dont print 1 sec sampled data (default on, off if !-T)
-  -T <sec test>	(default: 10 sec, for demo purposes)
-  -l <data/header lines>
-  -H <bucketcount>
-  -B <bucketsize ns>
+  -T <sec test>		 (default: 120 sec)
+  -l <data/header lines> (default 21)
+  -H <bucketcount>	 (default 100)
+  -B <bucketsize ns>	 (default 1000 ns)
+  -p <sample_period_us>	 (default 100 us)
 EOF
-    # NB: many defaults are coded in latency, klatency
+    # NB: many defaults are coded in latency
     exit 1
 }
 
+echo "xeno-test: started $*"
 #set -e	# ctrl-C's should end everything, not just subshells. 
 	# commenting it out may help to debug stuff.
 
 set -o notify	# see dd's finish immediately.(or not!)
 
+withBusybox=0
+if sh --help 2>&1| grep -q BusyBox; then
+    withBusybox=1;
+# else running a real /bin/sh (bash) shell
+fi
+echo withBusybox is $withBusybox
+pidFile=/var/lock/`basename $0.$$`.pids
+
+checkUtilities() {
+  # Check for needed helper utilities
+  local neededApplets="awk basename cut date dd dirname egrep grep getopt
+		       head kill md5sum mount sleep test top uname zcat"
+  local foundAll=1
+  for  _j in $neededApplets
+  do
+    if test -z "`which $_j`"; then
+      echo "Please build busybox with support for applet $_j"
+      foundAll=0
+    fi
+  done
+  if test $foundAll -eq 0 ; then exit 3 ; fi
+}
+
+checkHelpers() {
+  local foundAll=1
+  if test -z "`which script`" -a -n "$logging"; then
+      echo "You will not be able to log (-L option) as script is missing"
+      foundAll=0
+  fi
+  if test -z "`which mail`" -a "$sendit" = 'm' ; then
+      echo "You will not be able send mail (-m/-M options) as mail is missing"
+      foundAll=0
+  fi
+  if test -z "`which curl`" -a "$sendit" = 'm' ; then
+      echo "You will not be able to upload (-U option) as curl is missing"
+      foundAll=0
+  fi
+  if test $foundAll -eq 0 ; then exit 3 ; fi
+}
+
 loudly() {
     [ "$1" = "" ] && return
     # run task after announcing it
-    echo;  date;
+    echo; date;
     echo running: $*
-    $* &
+    eval $* &			# eval helps w complex cmds, like zegrep -E
     wait $!
 }
 
 # defaults for cpu workload 
 device=/dev/zero	
-typeset -a dd_jobs
-dd_jobs=()
+dd_jobs=
 
 # used in generate-loads
-mkload() { exec dd if=$device of=/dev/null $* ; }
+mkload() { dd if=$device of=/dev/null $* & }
 
 generate_loads() {
-    local jobsct=$1; shift;
+    local jobsct=$1;
+    # if test -z "$1"; then echo Skipping generate_loads; return; fi
+    shift 1
+    if test 0 -eq $withBusybox ; then
+	reaper() { echo something died a $! or $* ; sleep 1;  }
+	trap reaper CHLD
+	trap cleanup_load EXIT	# under all exit conditions
+    fi
+    while test $jobsct -ge 1; do 
+        jobsct=$((jobsct-1)); 
+        mkload
+        dd_jobs="$dd_jobs $!" ;
+    done
 
-    reaper() { echo something died $*; }
-    trap reaper CHLD
-    trap cleanup_load EXIT	# under all exit conditions
-    
-    for (( ; $jobsct ; jobsct-- )) ; do
-	mkload &
-	dd_jobs[${#dd_jobs[*]}]=$!
-    done;
-
-    echo dd workload started, pids ${dd_jobs[*]}
+    echo dd workload started, pids $dd_jobs stored in $pidFile
+    echo  $dd_jobs > $pidFile
 }
 
 cleanup_load() {
     # kill the workload
-    echo killing workload pids ${dd_jobs[*]}
-    kill ${dd_jobs[*]};
+    if test -z "$dd_jobs" -a -r $pidFile; then
+      dd_jobs=`cat $pidFile`
+      rm -f $pidFile
+    fi
+
+    if test -z "$dd_jobs" ; then
+        echo "cleanup_load: no dd_jobs found"
+    else
+	for _j in $dd_jobs
+	do
+	  ps | grep $_j
+	  kill $_j
+	done
+    fi
     unset dd_jobs;
 }
 
-boxinfo() {
-    # static info, show once
-    loudly cat /proc/cpuinfo | egrep -v 'bug|wp'
-    loudly cat /proc/meminfo
+whatconf="XENO|IPIPE|PREEMPT|CONFIG_ACPI|CONFIG_PM|CPU_FREQ|CONFIG_DEBUG_SPINLOCK|CONFIG_FRAME_POINTER"
+
+
+boxinfo() { # static info, show once
+    loudly `dirname $0`/xeno-config --verbose
+    loudly `dirname $0`/xeno-info
+
+    loudly cat /proc/cpuinfo	# bogomips changes under CPU_FREQ
+    loudly md5sum /proc/cpuinfo	'# cpuinfo fingerprint'
+
+    # how much of the config do we want ?
+    local filter=" grep -E '$whatconf'"
+    [ "$verbose" = 1 ] && filter=
+    if test -f /proc/config.gz; then # get the config
+         loudly zcat /proc/config.gz | $filter
+    elif test -f /lib/modules/`uname -r`/build/.config
+    then
+	loudly cat /lib/modules/`uname -r`/build/.config | $filter
+    fi
+
     [ -d /proc/adeos ] && for f in /proc/adeos/*; do loudly cat $f; done
     [ -d /proc/ipipe ] && for f in /proc/ipipe/*; do loudly cat $f; done
 }
 
-boxstatus() {
-    # get dynamic status (bogomips, cpuMhz change with CPU_FREQ)
+boxstatus() {     # get dynamic status
     loudly cat /proc/interrupts
     loudly cat /proc/loadavg
+    loudly cat /proc/meminfo
+
+    if [ -d /proc/xenomai ]; then
+	for f in /proc/xenomai/*;   do [ -f $f ] && loudly cat $f; done
+	for f in /proc/xenomai/*/*; do [ -f $f ] && loudly cat $f; done
+    fi
     [ -n "$prepost" ] && loudly $prepost
-    loudly top -bn1c | head -$(( 12 + $workload ))
+    if test 0 -eq $withBusybox ; then
+	loudly top -bn1c | head -n $(( 12 + $workload ))
+    else
+	loudly top | head -n $(( 12 + $workload ))
+    fi
 }
 
 
 run_w_load() {
     local opts="$*";
-    [ "$opts"  = '' ] && opts='-q -s -T 10'
+    [ "$opts"  = '' ] && opts='-sh -T 120'
 
     boxinfo
     loudly generate_loads $workload
     boxstatus
     (
-	cd ../testsuite/latency
-	#loudly ./run -- -T 10 -s -l 5
-	loudly ./run -- -h $opts
-
-	[ -n "$prepost" ] && loudly $prepost
-	
-	cd ../klatency
-	#loudly ./run -- -T 10 -s -l 5
-	loudly ./run -- -h $opts;
+        cd `dirname $0`/../testsuite/latency
+	loudly ./run --  $opts -t0
+	loudly ./run --  $opts -t1
+	loudly ./run --  $opts -t2
+    )
+    (	cd `dirname $0`/../testsuite/switch
+	loudly ./run --  '# switch'
+    )
+    (	cd `dirname $0`/../testsuite/cyclic
+	loudly ./run -- -p 10 -n -l 1000 '# cyclictest'
     )
     boxstatus
+    cleanup_load
 }
 
-
+#####################
+# MAIN
+checkUtilities
 
 if [ -f /proc/config.gz ] ; then
 
     # check/warn on problem configs
-    
-    eval `zgrep CONFIG_CPU_FREQ /proc/config.gz`;
+    eval `zcat /proc/config.gz | grep CONFIG_CPU_FREQ` ;
     if [ ! -z "$CONFIG_CPU_FREQ" ] ; then
 	echo "warning: CONFIG_CPU_FREQ=$CONFIG_CPU_FREQ may be problematic"
     fi
-
 fi
 
 workload=1	# default = 1 job
 
 # *pass get all legit options, except -N, -L
-pass=		# pass thru to latency, klatency
+pass=		# pass thru to latency
 loadpass=	# pass thru to subshell, not to actual tests
 
-# if both empty means no logging
-logfile=	#
-logprefix=
+logging=	# no logging by default
+logfile=test-`uname -r` # defaults to test-`uname -r`-<datestampe>
+logprefix=/tmp/	# someplace usually there
 prepost=	# command to run pre, and post test (ex ntpq -p)
 
-while getopts 'd:shqT:l:H:B:uLN:w:W:p:' FOO ; do
+email='xenomai-data@gna.org'		# may reject til you subscribe
+sentby='xenotest.sender@xenomai.org'	# tbd
+url=
+sendit=		# send it by m-mail, u-url
+verbose=
+dateargs='+%y%m%d.%H%M%S'
 
+sendit() {
+    local file=$1
+    if test "$sendit" = 'm' ; then
+	echo "mailing $file to $email"
+	if test -n "$file" ; then
+	    mail -s 'xeno-test results' $email -- -F $sentby < $file
+	else
+	    cat - | mail -s 'xeno-test results' $email -- -F $sentby
+	fi
+    elif test "$sendit" = 'u' ; then
+	echo "uploading $file to $url"
+	which curl && curl -T $file $url
+	# -x $proxy >/tmp/.submit_result
+	# which wget && curl -T $file $url \
+    else
+	echo "sendit unsupported option '$sendit'"
+    fi
+}
+
+handle_options() {	# called for XENOTEST_OPTS, ARGV
     case $FOO in
+
+	# latency passthrus
 	s|h|q)
 	    pass="$pass -$FOO" ;;
-	T|l|H|B)
+	T|l|H|B|p)
 	    pass="$pass -$FOO $OPTARG" ;;
+
+	# workload related
 	d) 
 	    device=$OPTARG    
 	    echo creating workload using dd if=$device
 	    if !(mount | grep -q ^$device) ; then
 		echo d option must be a block device, ie one of:
 		mount | cut -d\  -f1 | egrep -ve 'sysfs|proc|depts'
-		exit;
+		exit 1;
 	    fi
 	    loadpass="$loadpass -d $device"
 	    ;;
-	L)
-	    logfile=test-`uname -r`  ;;
-	N)
-	    logprefix=$OPTARG ;;
 	w)
 	    workload=$OPTARG
 	    loadpass="$loadpass -w $OPTARG"  ;;
 	W)
 	    altwork=$OPTARG
 	    loadpass="$loadpass -W '$OPTARG'"  ;;
-	p)
+	P)
 	    prepost=$OPTARG 
-	    loadpass="$loadpass -p '$OPTARG'"  ;;
+	    loadpass="$loadpass -P '$OPTARG'"  ;;
+
+	# output disposition
+	L)
+	    logging=1
+	    logfile=test-`uname -r`  ;;
+	N)
+	    logging=1
+	    logprefix=$OPTARG ;;
+	M)
+	    email=$OPTARG 
+	    sendit='m' ;;
+	m)
+	    sendit='m' ;;
+	U)
+	    url=$OPTARG 
+	    sendit='u' ;;
+	v)
+	    verbose=1 ;;
+	D)
+	    dateargs=$OPTARG ;;
 	?)
 	    myusage ;;
     esac
+}
+
+# process options from envar, then from cmd-line
+while getopts 'd:shqvT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO $XENOTEST_OPTS ; do
+    handle_options;
 done
+while getopts 'd:shqvT:l:H:B:uLN:w:W:p:mM:U:P:D:' FOO ; do
+    handle_options;
+done
+
+checkHelpers
 
 # all args have been handled, and split into 2 passthrus
 shift $(($OPTIND - 1));
 
-
-if [ "$logprefix$logfile" != "" ]; then
-    # restart inside a script invocation, passing all
-    date=`date +%y%m%d.%H%M%S`
-    script -c "./xeno-test $loadpass $pass $*" "$logprefix$logfile-$date"
-else
-    if [ "$altwork" != "" ]; then
-	mkload() { exec $altwork; }
-    fi
-    echo running $0 $pass $*
-    run_w_load $pass $*
+if test -f pidFile && ! test -w $pidFile ; then
+  echo  "pidfile $pidFile not writable "; 
+  exit 4
 fi
 
-exit;
+echo "xeno-test: running tests"
+
+wfile=$logprefix$logfile-`date $dateargs`
+if test "$logging" != "" ; then
+    # restart inside a script invocation, passing appropriate args
+    script -c "`dirname $0`/xeno-test $loadpass $pass $*" $wfile
+    res="$?"
+    if test "$res" == "0" ; then
+	sendit $wfile
+    fi
+else
+    if test "$altwork" != "" ; then
+	mkload() { exec $altwork; }
+    fi
+    run_w_load $pass $* 2>&1 | tee $wfile
+    res="$?"
+    if test "$sendit" != '' && test $res -eq 0  ; then
+       sendit $wfile
+    fi
+fi
+
+echo "xeno-test: finished"
+exit 0
+
 
 #################################################
 
@@ -209,7 +370,7 @@ Also, if it spawns subtasks, it should end them all when it gets SIGTERM.
    previous results.
 
 3. added -p 'command', which runs command before, between, and after
-   the latency and klatency tests.
+   the latency tests.
 
 
 TODO:
@@ -219,15 +380,20 @@ separate window, or when it finishes.  Forex, 'dd if=/dev/hda ...'
 will eventually finish, and should be restarted to keep the load up.
 Figure out why killall didnt work properly.
 
-2. Much more testing.  Heres a weak start..
+2. Much more testing.  Heres a weak start. You migth be better off
+using and improving test/test-xeno-test.rb.
 
 #!/bin/bash
 PATH=.:$PATH
 xeno-test -L
 xeno-test -N foo -T 18 -l 6 -s
 xeno-test -L -N foo1-
+xeno-test -m
+xeno-test -T 1 -M $USER@localhost
 xeno-test -N foo0 -w0 -l 5 -T 30 -h
 xeno-test -L -N foo4- -w4
 xeno-test -L -N foo4W- -w4 -W 'dd if=/dev/hda1 of=/dev/null'
 
-3.
+3. Repeat the same tests under the BusyBox.
+
+4. Check for border cases like missing awk, curl, mail, script, /proc/config.gz
