scripts/xeno-config: add --info option
Dumps the basic information we need about a system for investigating
an issue.

diff --git a/scripts/xeno-config-cobalt.in b/scripts/xeno-config-cobalt.in
--- a/scripts/xeno-config-cobalt.in
+++ b/scripts/xeno-config-cobalt.in
@@ -59,8 +59,28 @@ Options :
         --ldflags
         --lib*-dir,--libdir,--user-libdir
         --core
+        --info
 EOF
     exit $1
+}
+
+dump_info ()
+{
+    if test -r /proc/ipipe/version; then
+	uname -a 2>/dev/null || echo "cannot determine system information (uname?)"
+	echo "Kernel parameters: `cat /proc/cmdline`"
+	echo "I-pipe release #`cat /proc/ipipe/version` detected"
+	if test -r /proc/xenomai/version; then
+	    echo "Xenomai/cobalt `cat /proc/xenomai/version` detected"
+	else
+	    echo "Xenomai/cobalt disabled on this system"
+	fi
+    else
+	    echo "Xenomai/cobalt is NOT present on this system"
+    fi
+
+    eval echo "Configure args: @XENO_CONFIG_ARGS@"
+    exit 0
 }
 
 verbose ()
@@ -195,6 +215,9 @@ while test $# -gt 0; do
 	    ;;
         --help)
             usage 0 1>&2
+            ;;
+        --info)
+            dump_info
             ;;
         *)
          usage 1 1>&2
diff --git a/scripts/xeno-config-mercury.in b/scripts/xeno-config-mercury.in
--- a/scripts/xeno-config-mercury.in
+++ b/scripts/xeno-config-mercury.in
@@ -40,6 +40,7 @@ Options :
         --ldflags
         --lib*-dir,--libdir,--user-libdir
         --core
+        --info
 EOF
     exit $1
 }
@@ -54,6 +55,17 @@ verbose ()
     echo "        --arch=\"$XENO_TARGET_ARCH\""
     echo "        --prefix=\"$XENO_PREFIX\""
     echo "        --library-dir=\"$XENO_LIBRARY_DIR\""
+    exit 0
+}
+
+dump_info ()
+{
+    uname -a 2>/dev/null || echo "cannot determine system information (uname?)"
+    echo "Kernel parameters: `cat /proc/cmdline`"
+    if test -r /mnt/xenomai/system/version; then
+	echo "Xenomai/mercury `cat /mnt/xenomai/system/version` detected"
+    fi
+    eval echo "Configure args: @XENO_CONFIG_ARGS@"
 }
 
 if test $# -eq 0; then
@@ -163,6 +175,9 @@ while test $# -gt 0; do
 	    ;;
         --help)
             usage 0 1>&2
+            ;;
+        --info)
+            dump_info
             ;;
         *)
          usage 1 1>&2
