scripts/xeno-config: fix error message, dump_wrappers is not just POSIX
Signed-off-by: Henning Schild <henning.schild@siemens.com>

diff --git a/scripts/xeno-config-cobalt.in b/scripts/xeno-config-cobalt.in
--- a/scripts/xeno-config-cobalt.in
+++ b/scripts/xeno-config-cobalt.in
@@ -25,7 +25,7 @@ dump_wrappers()
 {
    file=$1
    if test \! -r ${XENO_LIBRARY_DIR}/$file; then
-      echo "Xenomai: POSIX wrappers cannot be read from ${XENO_LIBRARY_DIR}/${file}" >&2
+      echo "Xenomai: wrappers cannot be read from ${XENO_LIBRARY_DIR}/${file}" >&2
       exit 1
    fi
    if test "$LD_FILE_OPTION" = "yes"; then
